name: Discord Action

on:
  push:
    branches: [ main ]

jobs:
  react_on_push:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: >
            📢 Push i **${{ github.repository }}**\n
            Av: **${{ github.actor }}**\n
            Meddelande: _${{ github.event.head_commit.message }}_\n
            [Commit-länk](${{ github.event.head_commit.url }})