name: Discord Action

on:
  push:
    branches: [ main ]

jobs:
  react_on_push:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Ny push i frontend repot'
        
